"""
Shared sidebar branding for all pages.
Must be called in every page to persist across navigation.
"""

import streamlit as st


def render_sidebar() -> None:
    """
    Renders consistent sidebar branding and footer on every page.

    Visual order (controlled by CSS flex order):
      1. Brand header  (order: 0)
      2. Page nav       (order: 10) ← auto-generated by Streamlit
      3. Footer         (order: 20, margin-top: auto → pushed to bottom)
    """
    with st.sidebar:
        # ── Branding (top) ──
        st.markdown(
            """
            <div class="sidebar-brand">
                <div class="sidebar-brand-icon">🌿</div>
                <div>
                    <div class="sidebar-brand-name">Endo-AID</div>
                    <div class="sidebar-brand-version">Clinical Suite v2.0</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        # ── Footer  ──
        st.markdown(
            """
            <div class="sidebar-footer">
                <div class="sidebar-footer-label">Signed in as</div>
                <div class="sidebar-footer-name">Dr. Usuario Local</div>
                <div class="sidebar-footer-role">Oncología Digestiva</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
